config {
  type: "table",
  schema: require("../../includes/config").stage_dataset,
  name: "sales_stage"
}

js {
  const {
    raw_dataset
  } = require("../../includes/config");
}

SELECT DISTINCT
    UPPER(TRIM(Market)) AS Market,
    TRIM(DealerCode) AS DealerCode,
    CAST(MLI AS STRING) AS MLI,
    SAFE_CAST(Month AS INT64) AS Month,
    SAFE_CAST(Qty AS INT64) AS Qty,
    SAFE_CAST(Revenue AS NUMERIC) AS Revenue
FROM `${raw_dataset}.sales_data`
WHERE DealerCode IS NOT NULL
