INSERT INTO `ford-training-430008.training_config.file_ingestion_config`
(
  config_id,
  enabled,
  priority,
  file_pattern,
  source_format,
  sheet_name,
  target_project,
  target_dataset,
  target_table,
  write_disposition,
  autodetect,
  header_row,
  skip_rows,
  field_delimiter,
  encoding,
  expected_columns,
  target_schema,
  add_metadata_columns,
  description,
  created_at,
  updated_at
)
VALUES
(
  "sales_csv",
  TRUE,
  10,
  r"^landing/sales_data.*\.csv$",
  "CSV",
  NULL,
  "ford-training-430008",
  "janos_raw",
  "sales",
  "WRITE_APPEND",
  FALSE,
  1,
  0,
  ",",
  "utf-8",
  ["dealer_code", "market", "sales_date", "model", "units", "revenue"],
  [
    STRUCT("dealer_code" AS column_name, "STRING" AS data_type, "NULLABLE" AS mode),
    STRUCT("market" AS column_name, "STRING" AS data_type, "NULLABLE" AS mode),
    STRUCT("sales_date" AS column_name, "STRING" AS data_type, "NULLABLE" AS mode),
    STRUCT("model" AS column_name, "STRING" AS data_type, "NULLABLE" AS mode),
    STRUCT("units" AS column_name, "STRING" AS data_type, "NULLABLE" AS mode),
    STRUCT("revenue" AS column_name, "STRING" AS data_type, "NULLABLE" AS mode)
  ],
  TRUE,
  "CSV értékesítési fájl betöltése a RAW sales táblába. RAW rétegben szándékosan STRING-ként tartjuk az üzleti oszlopokat.",
  CURRENT_TIMESTAMP(),
  CURRENT_TIMESTAMP()
),
(
  "dealer_master_csv",
  TRUE,
  20,
  r"^landing/dealer_master.*\.csv$",
  "CSV",
  NULL,
  "ford-training-430008",
  "janos_raw",
  "dealer_master",
  "WRITE_TRUNCATE",
  FALSE,
  1,
  0,
  ",",
  "utf-8",
  ["dealer_code", "dealer_name", "market", "city"],
  [
    STRUCT("dealer_code" AS column_name, "STRING" AS data_type, "NULLABLE" AS mode),
    STRUCT("dealer_name" AS column_name, "STRING" AS data_type, "NULLABLE" AS mode),
    STRUCT("market" AS column_name, "STRING" AS data_type, "NULLABLE" AS mode),
    STRUCT("city" AS column_name, "STRING" AS data_type, "NULLABLE" AS mode)
  ],
  TRUE,
  "CSV dealer master fájl betöltése a RAW dealer_master táblába. Törzsadat jelleg miatt minden futásnál újratöltjük.",
  CURRENT_TIMESTAMP(),
  CURRENT_TIMESTAMP()
),
(
  "monthly_excel_sales_sheet",
  TRUE,
  30,
  r"^landing/monthly_sales.*\.xlsx$",
  "XLSX",
  "Sales",
  "ford-training-430008",
  "janos_raw",
  "sales",
  "WRITE_APPEND",
  FALSE,
  1,
  0,
  NULL,
  NULL,
  ["dealer_code", "market", "sales_date", "model", "units", "revenue"],
  [
    STRUCT("dealer_code" AS column_name, "STRING" AS data_type, "NULLABLE" AS mode),
    STRUCT("market" AS column_name, "STRING" AS data_type, "NULLABLE" AS mode),
    STRUCT("sales_date" AS column_name, "STRING" AS data_type, "NULLABLE" AS mode),
    STRUCT("model" AS column_name, "STRING" AS data_type, "NULLABLE" AS mode),
    STRUCT("units" AS column_name, "STRING" AS data_type, "NULLABLE" AS mode),
    STRUCT("revenue" AS column_name, "STRING" AS data_type, "NULLABLE" AS mode)
  ],
  TRUE,
  "Három sheetes Excel Sales sheetjének betöltése a RAW sales táblába.",
  CURRENT_TIMESTAMP(),
  CURRENT_TIMESTAMP()
),
(
  "monthly_excel_dealers_sheet",
  TRUE,
  40,
  r"^landing/monthly_sales.*\.xlsx$",
  "XLSX",
  "Dealers",
  "ford-training-430008",
  "janos_raw",
  "dealer_master",
  "WRITE_TRUNCATE",
  FALSE,
  1,
  0,
  NULL,
  NULL,
  ["dealer_code", "dealer_name", "market", "city"],
  [
    STRUCT("dealer_code" AS column_name, "STRING" AS data_type, "NULLABLE" AS mode),
    STRUCT("dealer_name" AS column_name, "STRING" AS data_type, "NULLABLE" AS mode),
    STRUCT("market" AS column_name, "STRING" AS data_type, "NULLABLE" AS mode),
    STRUCT("city" AS column_name, "STRING" AS data_type, "NULLABLE" AS mode)
  ],
  TRUE,
  "Három sheetes Excel Dealers sheetjének betöltése a RAW dealer_master táblába.",
  CURRENT_TIMESTAMP(),
  CURRENT_TIMESTAMP()
),
(
  "monthly_excel_mli_mapping_sheet",
  TRUE,
  50,
  r"^landing/monthly_sales.*\.xlsx$",
  "XLSX",
  "MLI Mapping",
  "ford-training-430008",
  "janos_raw",
  "mli_mapping",
  "WRITE_TRUNCATE",
  FALSE,
  1,
  0,
  NULL,
  NULL,
  ["model", "mli_code", "segment"],
  [
    STRUCT("model" AS column_name, "STRING" AS data_type, "NULLABLE" AS mode),
    STRUCT("mli_code" AS column_name, "STRING" AS data_type, "NULLABLE" AS mode),
    STRUCT("segment" AS column_name, "STRING" AS data_type, "NULLABLE" AS mode)
  ],
  TRUE,
  "Három sheetes Excel MLI Mapping sheetjének betöltése a RAW mli_mapping táblába.",
  CURRENT_TIMESTAMP(),
  CURRENT_TIMESTAMP()
);
